### PR TITLE
ignore .idea folder

### PR DESCRIPTION
**Pull request by prototype99**
prevents this happening all the time:
Screenshot_20240524_160326

### CODE REVIEW

**Comment by akarnokd** [comment]
Why are you doing these PRs?

**Comment by sophietheopossum** [comment]
noticed some things are missing, so getting ready to work on that

**Comment by akarnokd** [comment]
What exactly do you intend to work on?

**Comment by sophietheopossum** [comment]
#32 is what immediately comes to mind, might be other things i'm forgetting right now

**Pull request merged**
